from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from fastapi.responses import HTMLResponse
import json
import os

app = FastAPI(title="Fractal Generator")

# 1. Mount the folders 
app.mount("/static", StaticFiles(directory="static"), name="static")
app.mount("/gallery-images", StaticFiles(directory="Fractal-Gallery"), name="gallery-images")
# 2. Set up the Template engine
# This looks for your index.html inside the /templates folder
templates = Jinja2Templates(directory="templates")

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    # Default fallback data if the observer hasn't run yet
    data = {
        "temp": "N/A",
        "humidity": "N/A",
        "c_real": -0.7,
        "c_imag": 0.27
    }

    # 3. Path to the data generated by run_observer.py
    stats_path = "static/weather_stats.json"

    # 4. Try to load the live data
    if os.path.exists(stats_path):
        try:
            with open(stats_path, "r") as f:
                data = json.load(f)
        except Exception as e:
            print(f"Error reading stats: {e}")

    # 5. Return the template and "inject" the variables
    return templates.TemplateResponse("index.html", {
        "request": request,
        "temp": data.get("temp"),
        "humidity": data.get("humidity"),
        "c_real": data.get("c_real"),
        "c_imag": data.get("c_imag")
    })

@app.get("/gallery", response_class=HTMLResponse)
async def get_gallery(request: Request):
    # Path to your new gallery folder
    gallery_path = "Fractal-Gallery"
    
    # List all png files in the folder
    images = [f for f in os.listdir(gallery_path) if f.endswith('.png')]
    
    return templates.TemplateResponse("gallery.html", {"request": request, "images": images})